name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build-variant.yml
    with:
      CMAKE_PROJECT_DIR: ''
      CMAKE_CONFIG_PRESET: "github-actions"
      CMAKE_BUILD_PRESET: ''
      CMAKE_CONFIG: "Release"
      BINARY_DIR: "build"
      BINARY_NAME: ''
      BINARY_NAME_VAR: "NAME"
      BINARY_VERSION: ''
      BINARY_VERSION_VAR: "VERSION"
      TARGET_DIR: "build/src"
      VARIANT: "ng"
      VCPKG_COMMIT_ID: "66affb04e3b889a3210f7f24bef2fa93a557fa62"